import json

# Master generator for all 14 categories with 13-section comprehensive schema
SCHOLARSHIP_CATEGORIES = [
    {"id": 1, "name": "Central Government Scholarships", "code": "central_gov", "description": "National Scholarship Portal (NSP) schemes by Govt. of India for UG students.", "icon": "🏛️"},
    {"id": 2, "name": "Category-Based Scholarships", "code": "category_based", "description": "Specialized schemes for SC, ST, OBC, and Minority category students.", "icon": "👥"},
    {"id": 3, "name": "AICTE Scholarships", "code": "aicte", "description": "Technical, Engineering, and Pharmacy degree scholarships provided by AICTE.", "icon": "⚡"},
    {"id": 4, "name": "State Government Scholarships", "code": "state_gov", "description": "State-specific fee waivers and maintenance stipends across Indian states.", "icon": "🗺️"},
    {"id": 5, "name": "Merit-Based Scholarships", "code": "merit_based", "description": "Scholarships awarded purely on academic excellence and top rank performance.", "icon": "🏆"},
    {"id": 6, "name": "Need-Based Scholarships", "code": "need_based", "description": "Financial assistance for meritorious students from low-income families.", "icon": "🤝"},
    {"id": 7, "name": "Scholarships for Girls", "code": "girl_students", "description": "Dedicated funding initiatives promoting higher education for female students.", "icon": "👩‍🎓"},
    {"id": 8, "name": "Scholarships for Students with Disabilities (PwD)", "code": "pwd_students", "description": "Assistive allowances, device support, and tuition aid for PwD students.", "icon": "♿"},
    {"id": 9, "name": "Institutional Scholarships", "code": "institutional", "description": "Tuition waivers, sports quotas, and alumni funding from top institutes/universities.", "icon": "🎓"},
    {"id": 10, "name": "Sports Scholarships", "code": "sports", "description": "Financial aid and stipends for national, state, and university level athletes.", "icon": "🏅"},
    {"id": 11, "name": "Research and Innovation Scholarships", "code": "research_innovation", "description": "Grants for student innovators, patent holders, hackathons, and research projects.", "icon": "💡"},
    {"id": 12, "name": "International Scholarships for Indian UG Students", "code": "international", "description": "Study abroad grants and exchange programs in UK, USA, Germany, NZ.", "icon": "✈️"},
    {"id": 13, "name": "Corporate Scholarships", "code": "corporate", "description": "Philanthropic education scholarships from major corporations and foundations.", "icon": "🏢"},
    {"id": 14, "name": "Education Loan Interest Subsidy Schemes", "code": "loan_subsidy", "description": "Government interest subsidy support during moratorium period of education loans.", "icon": "💳"}
]

RAW_SCHOLARSHIPS = [
    # 1. Central Govt
    {
        "id": "pm_usp_csss",
        "category_id": 1,
        "category_name": "Central Government Scholarships",
        "scholarship_name": "PM-USP Central Sector Scheme of Scholarships (CSSS)",
        "scholarship_id_ref": "NSP/CSSS/2025-26",
        "provider_organization": "Department of Higher Education, Ministry of Education, Govt. of India",
        "provider_type": "Government",
        "purpose": "Financial assistance to meritorious students from low-income families to meet day-to-day expenses while pursuing higher education.",
        "description": "Provides ₹12,000/year for 1st-3rd year and ₹20,000/year for 4th year undergraduate study.",
        "detailed_description": "The Central Sector Scheme of Scholarship for College and University Students is implemented by the Department of Higher Education to provide financial assistance to meritorious students from poor families to meet a part of their day-to-day expenses while pursuing higher studies. 82,000 fresh scholarships are awarded every year (41,000 for boys and 41,000 for girls) across all States/UTs.",
        "official_website": "https://scholarships.gov.in",
        "contact_email": "helpdesk@nsp.gov.in",
        "contact_phone": "0120-6619540",
        "application_portal_url": "https://scholarships.gov.in",
        "scholarship_status": "Active",
        "announcement_date": "2025-07-01",
        "last_updated_date": "2026-08-20",

        "nationality": "Indian",
        "citizenship": "Indian Citizen",
        "domicile_restriction": "All States and Union Territories of India",
        "min_age": 17,
        "max_age": 25,
        "gender": "All",
        "caste_category": "All (SC, ST, OBC, General)",
        "minority_eligibility": "Eligible for all religious and linguistic minorities",
        "pwd_eligibility": "Yes (5% horizontal reservation for students with benchmark disability >= 40%)",
        "first_generation_requirement": "Not mandatory, but lower income families prioritized",
        "family_background": "All economic backgrounds with annual income <= Rs. 4.5 Lakhs",
        "employment_status": "Must not be in full-time gainful employment",
        "marital_status": "Unmarried / Married",
        "special_eligibility_conditions": "Must be pursuing regular full-time degree from recognized institute",

        "min_qualification": "Class 12th Board Examination (HSC / CBSE / ICSE)",
        "current_education_level": "Undergraduate",
        "eligible_courses": ["B.E.", "B.Tech", "B.Sc", "B.Com", "B.A.", "MBBS", "B.Pharm", "Law"],
        "eligible_departments": ["CSE", "ECE", "EEE", "IT", "CIVIL", "MECH", "BSC", "BCOM", "BA", "LAW"],
        "eligible_streams": "Engineering, Sciences, Humanities, Commerce, Medical, Law",
        "eligible_institutions": "All AICTE / UGC / State / Central recognized colleges and universities",
        "min_percentage": 80.0,
        "min_gpa": 7.5,
        "required_specific_subjects": "Relevant stream subjects in Class 12th Board Exam",
        "previous_year_requirement": "Top 20th percentile in the respective State/Central Board Examination",
        "eligible_years": [1, 2, 3, 4],
        "backlog_restrictions": "No standing backlogs/arrears permitted for annual renewals (minimum 50% marks in each annual exam)",
        "admission_status_requirement": "Regular, full-time student admitted through counseling or merit",

        "max_income": 450000.0,
        "max_income_label": "₹4.5 Lakhs / annum",
        "income_certificate_required": "Yes (Mandatory)",
        "accepted_income_authority": "Tehsildar / Sub-Divisional Magistrate (SDM) / Revenue Authority",
        "income_calculation_method": "Gross annual family income from all sources",
        "ews_requirement": "Income certificate valid for current financial year",
        "economic_category": "Below ₹4.5 Lakhs / Low Income",
        "income_proof_documents": ["Revenue Dept Income Certificate", "Salary Slip / Form 16 / ITR of parents"],
        "income_differs_by_state": "Uniform across all States (₹4.5 Lakhs)",

        "benefits": "₹12,000/year (1st-3rd year), ₹20,000/year in 4th year professional courses",
        "monthly_amount": "₹1,000 - ₹1,667 / month equivalent",
        "annual_amount": "₹12,000 (Years 1-3) & ₹20,000 (Year 4)",
        "one_time_amount": "N/A",
        "tuition_fee_coverage": "Direct cash grant toward study and maintenance expenses",
        "hostel_fee_coverage": "Included in annual stipend grant",
        "mess_allowance": "Included in annual stipend grant",
        "books_allowance": "Included in annual stipend grant",
        "laptop_device_allowance": "N/A",
        "travel_allowance": "N/A",
        "examination_fee_coverage": "Included in grant",
        "maintenance_allowance": "₹12,000 - ₹20,000 / year",
        "other_benefits": "Direct Benefit Transfer (DBT) credit into Aadhaar-seeded bank account via PFMS",
        "max_total_benefit": "₹56,000 over 4-year undergraduate engineering degree",
        "duration_years": 4,
        "renewal_benefits": "Guaranteed annual renewal upon maintaining 50%+ marks and 75%+ attendance",

        "application_opening_date": "15th July 2025",
        "application_closing_date": "30th November 2025",
        "application_method": "Online (National Scholarship Portal - NSP)",
        "application_portal": "https://scholarships.gov.in",
        "registration_process": "One-Time Registration (OTR) with Aadhaar & Mobile OTP on NSP Portal",
        "login_requirements": "OTR Number, Password, Aadhaar Face/OTP Authentication",
        "application_fee": "Free of Cost (Zero Application Fee)",
        "step_by_step_procedure": "1. Complete NSP OTR -> 2. Fill Application Form -> 3. Upload Documents -> 4. Institute Verification (L1) -> 5. State Nodal Officer Verification (L2) -> 6. DBT Payment Disbursed",
        "application_deadline": "30th November annually (Institute verification till 15th December)",
        "correction_window": "Available for 15 days following defect marking by College Nodal Officer",
        "document_upload_requirements": "Scanned PDF/JPEG files under 200KB",
        "application_tracking_method": "Track Application Status via NSP Login & PFMS Portal",

        "necessary_documents": [
            "Aadhaar Card of Student (Mandatory)",
            "Class 12th Board Marksheet & Passing Certificate (Mandatory)",
            "Annual Family Income Certificate issued by Tehsildar (Mandatory)",
            "College Bonafide Student Certificate & Verification Form (Mandatory)",
            "Student Bank Account Passbook (Aadhaar Seeded) (Mandatory)",
            "Passport Size Photograph & Signature (Mandatory)",
            "Community / Caste Certificate (Mandatory for SC/ST/OBC quotas)"
        ],

        "selection_criteria": "Merit-cum-Means based on Class 12 Board Examination Top 20th Percentile cut-offs",
        "is_merit_based": True,
        "is_need_based": True,
        "is_first_come_first_served": False,
        "entrance_exam_required": False,
        "interview_required": False,
        "document_verification_levels": "Two-Level: 1. College Nodal Officer -> 2. State/District Nodal Officer",
        "shortlisting_process": "Merit lists generated by State Education Boards according to allotted quotas",
        "weightage_marks": "100% Board Marks rank among applicants meeting income criteria",
        "weightage_financial_need": "Income must be <= ₹4.5 Lakhs",
        "special_category_preference": "50% reserved for girls; SC/ST/OBC/General allocated per national norms",
        "total_scholarships_available": 82000,
        "selection_announcement_date": "January annually",

        "renewal_eligibility": "Annual renewal for duration of undergraduate course upon passing",
        "min_renewal_marks": "50% marks in previous annual/semester examinations",
        "min_attendance_pct": 75,
        "max_allowed_backlogs": "0 Standing Backlogs at time of renewal",
        "renewal_deadline": "Same as fresh application closing date on NSP",
        "renewal_procedure": "Submit Renewal Application on NSP with previous year marksheet and bonafide",
        "renewal_documents": ["Previous Year Marksheets", "Institute Bonafide", "Attendance Certificate"],
        "max_renewal_period": "Up to 4 years for Engineering (5 years for Integrated/Medical)",
        "cancellation_conditions": "Dropping out, failure in examinations, disciplinary action, or false income declarations",
        "income_recertification_required": "Yes, annual re-verification on NSP",

        "who_cannot_apply": "Students pursuing diploma, correspondence/distance courses, or private candidates",
        "already_receiving_another_scholarship": "Not allowed (Cannot hold two Central/State govt scholarships concurrently)",
        "multiple_scholarships_allowed": False,
        "govt_employee_child_restriction": "Allowed provided annual family income is <= ₹4.5 Lakhs",
        "institution_restrictions": "Unrecognized or unaccredited institutions excluded",
        "course_restrictions": "Distance / Online mode degree programs not eligible",
        "duplicate_application_penalty": "Immediate cancellation and blacklisting on NSP portal",

        "rural_students_preference": "State quota allocations ensure representation from rural districts",
        "female_student_preference": "50% of total 82,000 scholarship slots reserved for girl students",
        "minority_preference": "Proportionate allocation per state demographics",
        "pwd_quota": "5% horizontal reservation for students with benchmark disabilities",
        "special_circumstances": "Merit-cum-means quota across all streams (Science, Commerce, Humanities)",

        "important_dates": {
            "opening_date": "15th July 2025",
            "closing_date": "30th November 2025",
            "correction_date": "1st - 15th December 2025",
            "verification_date": "15th December 2025",
            "shortlist_date": "15th January 2026",
            "interview_date": "N/A (No Interview)",
            "result_date": "31st January 2026",
            "disbursement_date": "February - March 2026"
        },

        "contact_authority": {
            "authority_name": "National Scholarship Division, Ministry of Education, Govt. of India",
            "official_website": "https://scholarships.gov.in",
            "official_email": "helpdesk@nsp.gov.in",
            "helpline_number": "0120-6619540",
            "office_address": "Shastri Bhawan, Dr. Rajendra Prasad Road, New Delhi - 110001",
            "application_url": "https://scholarships.gov.in",
            "official_notification_url": "https://www.education.gov.in/scholarships-education-loan-0",
            "verification_url": "https://scholarships.gov.in/public/schemeWiseNodalOfficerDetails",
            "last_verified_date": "2026-08-20",
            "source_authority": "Ministry of Education & National Informatics Centre (NIC)"
        }
    }
]

print("Ready to enrich scholarships...")
